server:
  port: 8001  #服务器端口

spring:
  application:
    name: SERVICE-PROVIDER

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #eurake服务注册地址

logging:
  level:
    root: DEBUG