server:
  port: 8088

spring:
  application:
    name: SERVICE-CONSUMER

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #eurake服务注册地址

feign:
  hystrix:
    enabled: true